### ISSUE TITLE
Hello, help me change the script.

### ISSUE THREAD

**Issue by VasianRed** [bastimeyer/dayz-linux-cli-launcher#13]
I wrote to you https://github.com/bastimeyer/dayz-linux-cli-launcher/issues/11 , help me with the script, I don't know the programming language(((

**Comment by bastimeyer** [comment]
I've already told you to read the readme, which you apparently have not done.

> Help me change the script

What are you actually asking for here? lol...

----

> [dayz-launcher.sh ][info] Resolving steam
> [dayz-launcher.sh][info] Using non-flatpak mode: steam
> [dayz-launcher.sh][error] Invalid/missing directory: /home/red_linux/.local/share/Steam/steamapps/common/DayZ

If you have installed the game in a different location which is not the default, then you need to set the `STEAM_ROOT` environment variable, which is explained in the readme or `--help` text.

> Environment variables:
>
>  STEAM_ROOT
>    Set a custom path to Steam's root directory. Default is:
>    ${XDG_DATA_HOME:-${HOME}/.local/share}/Steam
>    which defaults to ~/.local/share/Steam
>
>    If the flatpak package is being used, then the default is:
>    ~/.var/app/com.valvesoftware.Steam/data/Steam
>
>    If the game is stored in a different Steam library directory, then this
>    environment variable needs to be set/changed.
>
>    For example, if the game has been installed in the game library located in
>      /media/games/SteamLibrary/steamapps/common/DayZ
>    then the STEAM_ROOT env var needs to be set like this:
>      STEAM_ROOT=/media/games/SteamLibrary

> Examples
> ```sh
> # run game from a different Steam games library path
> STEAM_ROOT=/media/games/SteamLibrary ./dayz-launcher.sh launch arguments...
> ```

As you can see in the quoted text above, the default path is `~/.local/share/Steam`, aka. `/home/red_linux/.local/share/Steam` on your system.

If Fedora 36's Steam package overrides Steam's default install path, then you have to change the `STEAM_ROOT` env var. It is impossible for the launcher script to automatically find this, because it can be located anywhere, and this can differ from distro to distro. If your distro does do things differently compared to the default, then you have to deal with that. Debian is another example of this and it sets up steam in a different location in the user's home directory.

This is all I can (and am willing to) do to help you with this. As said and shown, this is already documented. If you're a Linux beginner who is overwhelmed by this, then I can't help you anyway. Good luck.

**Comment by VasianRed** [comment]
if [[ -z "${STEAM_ROOT}" ]]; then
    if [[ "${STEAM}" == flatpak ]]; then
      STEAM_ROOT="${HOME}/.var/app/${FLATPAK_STEAM}/data/Steam"
    else
      STEAM_ROOT="${XDG_DATA_HOME:-${HOME}/d0352141-8e42-43e5-b3c0-63b770a65953/SteamGames}"
    fi
  fi

**Comment by bastimeyer** [comment]
No, you did not, because you don't have to change/modify the launcher. This is an **environment variable** which you need to set while executing the launcher script. If you don't know what environment variables are, then google it. I have already explained this twice and copied the example from the readme.

Going to lock this now, since you're unwilling to read. Sorry, but I don't want to waste my time with this.
