### ISSUE TITLE
error: com.valvesoftware.Steam/*unspecified*/*unspecified* not installed

### ISSUE THREAD

**Issue by witmak38** [bastimeyer/dayz-linux-cli-launcher#2]

**Comment by bastimeyer** [comment]
This is just an unsuppressed `stderr` output of the `flatpak info com.valvesoftware.Steam` command, when the launcher tries to check whether the flatpak package is installed. This it can be ignored as it continues with the non-flatpak steam version when the flatpak package is not installed.

Fixed in ab884462aae4f68144fb591b4d9b4f2063279490
https://github.com/bastimeyer/dayz-linux-cli-launcher/blob/master/CHANGELOG.md#011---2021-12-08
