### ISSUE TITLE
Can't find dayz 

### ISSUE THREAD

**Issue by BRINGit34** [bastimeyer/dayz-linux-cli-launcher#5]
While using this the .sh file could not find my dayz install. My dayz is installed at /home/user/.steam/debian-installation/steamapps/common/DayZ and I believe it is installed here due to me getting it from the ubuntu repos. But when I try to change where the launcher looks for the game I can't redirect it to this file because it always adds a /Steam/steamapps/common/DayZ to the end of where I change it to. And I am going to be honest I have zero coding knowledge so I don't really know how to solve this problem. I understand that this is mostly due to my ignorance with coding but I think it would be nice if the launcher automatically checked for this path since a lot of people use the ubuntu repos to install steam and from my understanding this is the default path that creates. Just my two cents. Sorry if I have done something wrong and this is wholly my fault

**Comment by bastimeyer** [comment]
https://github.com/bastimeyer/dayz-linux-cli-launcher#usage

> Environment variables:
> 
> STEAM_ROOT
>   Set a custom path to Steam's root directory. Default is:
>   ${XDG_DATA_HOME:-${HOME}/.local/share}/Steam
>   which defaults to ~/.local/share/Steam
> 
>   If the flatpak package is being used, then the default is:
>   ~/.var/app/com.valvesoftware.Steam/data/Steam
> 
>   If the game is stored in a different Steam library directory, then this
>   environment variable needs to be set/changed.

----

> My dayz is installed at /home/user/.steam/debian-installation/steamapps/common/DayZ

`~/.steam` is a deprecated fallback path created by Steam for legacy software reasons and it only includes symlinks to the actual install directories. The default Steam installation path is `${XDG_DATA_HOME:-${HOME}/.local/share/Steam}`, which defaults to `~/.local/share/Steam`, which this launcher properly uses as the default, as shown above.

https://wiki.archlinux.org/title/Steam#Directory_structure

> because it always adds a /Steam/steamapps/common/DayZ to the end of where I change it to

https://github.com/bastimeyer/dayz-linux-cli-launcher/blob/0.2.0/dayz-launcher.sh#L264-L271

As you can see, all it does is that it appends `/steamapps` to the `STEAM_ROOT` value, nothing else. The default value of `STEAM_ROOT` is `~/.local/share/Steam`, the default path of Steam's install directory that includes the default games library. If your game is installed in a different games library, then you have to set the right value of the `STEAM_ROOT` environment variable, the root path of the game library where DayZ is installed in.

If your Steam setup for some very weird reason does not use the standard directory layout, then you can still override the `STEAM_ROOT` env var and point it to the right directory with the appended `/steamapps` part in mind.

> I think it would be nice if the launcher automatically checked for this path

The file where Steam stores the user's configured game library folders (which is `${XDG_DATA_HOME:-${HOME}/.local/share/Steam}/steamapps/libraryfolders.vdf`) uses a custom format called VDF, and since the launcher is a simple BASH script, I'm not going to write a parser for that. There are VDF parsers for Python for example, so if the launcher was built in Python I would integrate that, but not in the current state. I also don't want to add external third party dependencies for the BASH script, as that would make the setup way more difficult for end users, as the launcher is not packaged software.

You simply have to manually set the proper `STEAM_ROOT` for now.

**Comment by BRINGit34** [comment]
Okay so it no longer gives an error and it should be going to the right path but now it simply does nothing. It says
`Resolving steam 
`Using non-flatpak mode:  steam
And then it does nothing but it is still running so I am confused

**Comment by bastimeyer** [comment]
> it simply does nothing

Post the entire command you're trying to run. You either have not provided any mod-ID or server address, or you've not set the `--launch` parameter. In that case there is nothing to do for the script. I suggest you read the `--help` text again.

**Comment by BRINGit34** [comment]
Okay I fixed it. For some reason me exiting steam and re-entering steam fixed my problem. But thank you for assistance
